"""create generated_combinations, simulations, results tables

Revision ID: 2f0e51283d21
Revises: f229c6789f80
Create Date: 2025-05-16 14:50:01.361729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0e51283d21'
down_revision: Union[str, None] = 'f229c6789f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_combinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithm_id', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('numbers', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('strong', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('used_in_real_draw', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_combinations_id'), 'generated_combinations', ['id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('sim_type', sa.String(), nullable=True),
    sa.Column('rows_generated', sa.Integer(), nullable=False),
    sa.Column('avg_hits', sa.Float(), nullable=True),
    sa.Column('total_prize', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_id'), 'simulations', ['id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combination_id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('strong_hit', sa.Boolean(), nullable=False),
    sa.Column('prize', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['combination_id'], ['generated_combinations.id'], ),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_simulations_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_generated_combinations_id'), table_name='generated_combinations')
    op.drop_table('generated_combinations')
    # ### end Alembic commands ###
